### ISSUE TITLE
Hyperion 0.10.0 breaks akka.net compatibility 

### ISSUE THREAD

**Issue by OnurGumus** [akkadotnet/Hyperion#212]
Hyperion 0.10.0 breaks akka.net compatibility where as 0.9.17 works fine

     System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.MissingMethodException: Method not found: 'Void Hyperion.SerializerOptions..ctor(Boolean, Boolean, System.Collections.Generic.IEnumerable`1<Hyperion.Surrogate>, System.Collections.Generic.IEnumerable`1<Hyperion.SerializerFactories.ValueSerializerFactory>, System.Collections.Generic.IEnumerable`1<System.Type>, Boolean)'.
         at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system, HyperionSerializerSettings settings)
         at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system)
         --- End of inner exception stack trace ---
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
         at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
         at Akka.Actor.Internal.ActorSystemImpl.ConfigureSerialization()
         at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config, ActorSystemSetup setup, Nullable`1 guardianProps)
         at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
         at Akka.Actor.ActorSystem.Create(String name, Config config)

**Comment by Aaronontheweb** [comment]
Looks like it - we must have not introduced those options changes in a backwards-compatible way earlier @Arkatufus

**Comment by Arkatufus** [comment]
I'll check this ASAP, sorry for the problem
