### ISSUE TITLE
Hyperion fails to serialize arrays of user defined structs

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Hyperion#232]
Hyperion failed to serialize array with exception:
```
[WARNING][7/1/2021 3:04:15 PM][Thread 0039][REDACTED] Association with remote system REDACTED has failed; address is now gated for 5000 ms. Reason is: [Akka.Remote.EndpointException: Failed to write message to the transport ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Hyperion.SerializerFactories.ArraySerializerFactory.WriteValues<System.ValueType>(System.ValueType[], System.IO.Stream, System.Type, Hyperion.ValueSerializers.ValueSerializer, Hyperion.SerializerSession)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , ArraySerializerFactory , Object , Stream , Type , ValueSerializer , SerializerSession )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Hyperion.SerializerFactories.ArraySerializerFactory.<>c__DisplayClass4_0.<BuildSerializer>b__1(Stream stream, Object arr, SerializerSession session)
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Hyperion.Extensions.StreamEx.WriteObject(Stream stream, Object value, Type valueType, ValueSerializer valueSerializer, Boolean preserveObjectReferences, SerializerSession session)
   at lambda_method(Closure , Stream , Object , SerializerSession )
   at Akka.Serialization.HyperionSerializer.ToBinary(Object obj)
   at Akka.Remote.Serialization.DaemonMsgCreateSerializer.Serialize(Object obj)
   at Akka.Remote.Serialization.DaemonMsgCreateSerializer.PropsToProto(Props props)
   at Akka.Remote.Serialization.DaemonMsgCreateSerializer.ToBinary(Object obj)
   at Akka.Remote.MessageSerializer.Serialize(ExtendedActorSystem system, Address address, Object message)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   --- End of inner exception stack trace ---
   at Akka.Remote.EndpointWriter.PublishAndThrow(Exception reason, LogLevel level, Boolean needToThrow)
   at Akka.Remote.EndpointWriter.WriteSend(Send send)
   at Akka.Remote.EndpointWriter.<Writing>b__27_0(Send s)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ActorCell.<>c__DisplayClass114_0.<Akka.Actor.IUntypedActorContext.Become>b__0(Object m)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Phobos.Actor.PhobosActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
```

Need to investigate more

**Comment by Arkatufus** [comment]
Possible cause: 
Changes in exception type thrown from the deserialization confused part of Akka because some code is expecting or ignoring certain types of exception errors.

Preliminary observation:
Quite unlikely, exception thrown from a serializer should be bubbled up all the way, at least to the actor level.

**Comment by Arkatufus** [comment]
Possible cause:
Hyperion failed to deserialize array of struct

Test result:
Array of structs failed with these stack trace that mimics one of the customer reported error:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
The best overloaded method match for 'Hyperion.SerializerFactories.ArraySerializerFactory.WriteValues<System.ValueType>(System.ValueType[], System.IO.Stream, System.Type, Hyperion.ValueSerializers.ValueSerializer, Hyperion.SerializerSession)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , ArraySerializerFactory , Object , Stream , Type , ValueSerializer , SerializerSession )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Hyperion.SerializerFactories.ArraySerializerFactory.<>c__DisplayClass4_0.<BuildSerializer>b__1(Stream stream, Object arr, SerializerSession session) in D:\git\akkadotnet\Hyperion\src\Hyperion\SerializerFactories\ArraySerializerFactory.cs:line 71
   at Hyperion.ValueSerializers.ObjectSerializer.WriteValue(Stream stream, Object value, SerializerSession session) in D:\git\akkadotnet\Hyperion\src\Hyperion\ValueSerializers\ObjectSerializer.cs:line 105
   at Hyperion.Serializer.Serialize(Object obj, Stream stream) in D:\git\akkadotnet\Hyperion\src\Hyperion\Serializer.cs:line 162
   at Hyperion.Tests.PrimitivesTest.SerializeAndAssert[T](T[] expected) in D:\git\akkadotnet\Hyperion\src\Hyperion.Tests\PrimitivesTests.cs:line 264
   at Hyperion.Tests.PrimitivesTest.CanSerializeStructArray() in D:\git\akkadotnet\Hyperion\src\Hyperion.Tests\PrimitivesTests.cs:line 234
```

**Comment by Arkatufus** [comment]
Possible cause:
Hyperion somehow mangled the Int32 and Int64 wire format between linux and windows

Test result:
Can not reproduce, the only way for a message to fail with a cast exception during remoting is when the message class of the sender and the receiver uses a different type for a field or property.

**Comment by Arkatufus** [comment]
- [ ] Possible cause:
    Recent changes in how cross platform serialization support was set up might broke serialization.
