### ISSUE TITLE
Issues with Int64 mutation into Int32 during distributed pub sub messaging between linux and windows host

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Hyperion#234]
Int64 is somehow being serialized into Int32 in the wire format inside a distributed pub sub between linux and windows host.

```
2021-06-22 07:47:10 ERR AssociationError [REDACTED] -> REDACTED: Error [Unable to cast obje
ct of type 'System.Int32' to type 'System.Int64'.] [ 
   at lambda_method132(Closure , Stream , DeserializerSession )
   at Hyperion.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
   at lambda_method130(Closure , Stream , DeserializerSession )
   at Hyperion.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
   at Hyperion.Serializer.Deserialize[T](Stream stream)
   at Akka.Serialization.HyperionSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.MessageSerializer.Deserialize(ExtendedActorSystem system, Payload messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
   at lambda_method60(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
```

**Comment by Arkatufus** [comment]
Attempted to reproduce the bug in this branch: https://github.com/akkadotnet/akka.net/pull/5134
Could not reproduce the mutation problem.

**Comment by Aaronontheweb** [comment]
Resolved via https://github.com/akkadotnet/Hyperion/pull/236

**Comment by Arkatufus** [comment]
As a reference, original issue was caused by different string sorting algorithm in different platforms.
